import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, "../../");

const addressesPath = path.join(rootDir, "blockchain", "deployed_addresses.json");
const registryArtifactPath = path.join(
  rootDir,
  "blockchain",
  "artifacts",
  "contracts",
  "MediaCopyrightRegistry.sol",
  "MediaCopyrightRegistry.json"
);
const marketplaceArtifactPath = path.join(
  rootDir,
  "blockchain",
  "artifacts",
  "contracts",
  "LicensingMarketplace.sol",
  "LicensingMarketplace.json"
);
const targetPath = path.join(rootDir, "frontend", "src", "contractsConfig.js");

try {
  console.log("Syncing contract configurations to frontend...");
  if (!fs.existsSync(addressesPath)) {
    console.error("deployed_addresses.json not found. Deploy contracts first.");
    process.exit(1);
  }

  const addresses = JSON.parse(fs.readFileSync(addressesPath, "utf-8"));
  const registryArtifact = JSON.parse(fs.readFileSync(registryArtifactPath, "utf-8"));
  const marketplaceArtifact = JSON.parse(fs.readFileSync(marketplaceArtifactPath, "utf-8"));

  const configContent = `// Automatically generated by syncFrontend.js. Do not edit directly.
export const CONTRACT_ADDRESSES = ${JSON.stringify(addresses, null, 2)};

export const REGISTRY_ABI = ${JSON.stringify(registryArtifact.abi, null, 2)};

export const MARKETPLACE_ABI = ${JSON.stringify(marketplaceArtifact.abi, null, 2)};
`;

  // Create target directory if it doesn't exist
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, configContent, "utf-8");
  console.log(`Sync completed! Frontend config written to ${targetPath}`);
} catch (error) {
  console.error("Failed to sync frontend config:", error);
}
